MYSQL_URL : jdbc:mysql://localhost:3307/mypet
MYSQL_DATABASE : mypet
MYSQL_USER : root
MYSQL_PASSWORD : password

JWT_SECRET_KEY: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9MTLsobDtlITroZzsoJ3tirhjaGFubGxlZ2XsnoXri4jri6Qh
JWT_ACCESS_TOKEN_EXPIRATION: 3000000
JWT_REFRESH_TOKEN_EXPIRATION: 1209600000