### admin - 로그인
POST /api/auth/login HTTP/1.1
Host: {{root-path}}
Content-Type: application/json

{
  "email": "admin@mypet.com",
  "password": "admin1234"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
%}

### 유저 전체조회
GET /api/admin/user-manage HTTP/1.1
Host: {{root-path}}
Authorization: {{Authorization}}

### 유저 상태 변경 - 정지제외
PUT /api/admin/user-manage/{{userId}}/status HTTP/1.1
Host: {{root-path}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "status": "ACTIVE"
}

### 유저 상태 변경 - 정지
PUT /api/admin/user-manage/{{userId}}/status HTTP/1.1
Host: {{root-path}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "status": "SUSPENSION",
  "suspensionIssue": "그냥!"
}

### 유저 권한 변경
PUT /api/admin/user-manage/{{userId}}/role HTTP/1.1
Host: {{root-path}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "role": "USER"
}

### 신고 목록 전체조회
GET /api/admin/report-view HTTP/1.1
Host: {{root-path}}
Authorization: {{Authorization}}

### 신고 상태 변경
PUT /api/admin/report-view/{{reportId}}/report-status HTTP/1.1
Host: {{root-path}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "reportStatus": "IN_PROGRESS"
}

### 정지 목록 전체조회
GET /api/admin/suspension-view HTTP/1.1
Host: {{root-path}}
Authorization: {{Authorization}}

### 게시물 전체조회
GET /api/admin/post-manage HTTP/1.1
Host: {{root-path}}
Authorization: {{Authorization}}

### 게시물 전체조회 - 비공개
GET /api/admin/post-manage?postStatus=INACTIVE HTTP/1.1
Host: {{root-path}}
Authorization: {{Authorization}}
